### ISSUE TITLE
Plot ugly når kun 2 efforts

### ISSUE THREAD

**Issue by elfishlab** [elfishlab/elfish#34]
Plot er en ugly ass bitch når man kun har 2 efforts. Hva med å kun gi plot for k=>2? Hvis brukeren trykker på plot-knappen ved k=1 eller k=2 kan det komme opp en boble som sier "Plot only available for 3 or more efforts". Hva tror dere om det?

**Comment by pgdr** [comment]
Har disablet plot ved k < 3.

**Comment by pgdr** [comment]
Kan legge inn noe tekst som sier noe.  @semafor hadde noen tanker her.
