### ISSUE TITLE
Ingen øvre grense for N^?

### ISSUE THREAD

**Issue by elfishlab** [elfishlab/elfish#48]
Nå leter appen etter verdier langt opp i milliardene (uten at den er treig av den grunn tydeligvis). Vi må vel sette en eller annen øvre grense for N^? 100.000 ble diskutert som en akseptabel grense.

Relatert:
Problem-vektoren 1,3. Hvorfor gir den nå N/A for Zippin, selv om den leter etter superhøye verdier? Tidligere ga den jo N^ = ca. 650000 for den vektoren, som var feil, og vi fant ikke ut hvorfor.

**Comment by pgdr** [comment]
Den leter i intervallet `[T, T + 300 000]`.

Se setting [`window.elfish.upperlimit`](https://github.com/elfishlab/elfish/blob/master/assets/scripts/elfish.js#L3).

**Comment by pgdr** [comment]
Velg _reopen issue_  dersom du mener det er noe som ikke stemmer med logikken.
