### ISSUE TITLE
Må være mulig å slette efforts

### ISSUE THREAD

**Issue by elfishlab** [elfishlab/elfish#52]

**Comment by elfishlab** [comment]
I tilfelle man kommer borti +-knappen.

**Comment by pgdr** [comment]
Nå kan du prøve å "undo" legging til av nye efforts.  (Krever clear.)  Den er suboptimal nå, men er starten på en _undo_-funksjonalitet.

**Comment by pgdr** [comment]
(Bare så det er sagt er det lurt å alltid begynne med en _clear_ nå når vi utvikler fordi vi konstant endrer datastrukturene.  Eller ihvertfall dersom noe ikke fungerer som forventet kan det være grunnet en endring i datastrukturene som derfor krever _clear_ altså.)

((Lukker denne, _reopen_ hvis du ønsker sletting av bestemte efforts.))
